version: "3.9"

services:

  file_service:
    build:
      context: .
      dockerfile: mcp_server/Dockerfile
    container_name: file_service
    ports:
      - "8001:8001"
    environment:
      - BASE_DIR=/app/data
    volumes:
      - ./data:/app/data

  gateway_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway_api
    ports:
      - "8002:8002"
    environment:
      - FILE_SERVICE_URL=http://file_service:8001
    depends_on:
      - file_service